apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: modeling-api-trigger-binding
  labels:
  {{- include "modeling-api-deployment.labels" . | nindent 4 }}
spec:
  params:
  - name: action
    value: $(body.action)
  - name: registry_url
    value: {{ .Values.registry_url }}
  - name: chart_name
    value: {{ .Values.chart_name }}
  - name: chart_version
    value: {{ .Values.chart_version }}
  - name: namespace
    value: {{ .Release.Namespace }}